// src/veil/veil.service.ts
//
// Orchestrates:
//   1. DEPOSIT:  generate note (secret + nullifier), compute Poseidon commitment,
//                register note in Soroban pool contract, store encrypted note.
//   2. PAY:      decrypt note, compute ZK proof with snarkjs, submit withdrawal
//                tx to Soroban pool contract (which routes USDC to Cheese hot wallet).
//
// The snarkjs proof generation runs fully off-chain in this Node.js process.
// The Soroban contract verifies the proof on-chain using BN254 host functions.

import * as crypto from 'crypto';
import * as path from 'path';
import { Injectable, Logger, NotFoundException, BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import * as StellarSdk from '@stellar/stellar-sdk';
import { ShieldedNote, ShieldedNoteStatus } from './entities/shielded-note.entity';
import { SpentNullifier } from './entities/spent-nullifier.entity';
import { DepositDto, PayInvoiceDto } from './dto';

// Dynamic imports for snarkjs + circomlibjs (CommonJS modules — no TS types shipped)
// eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
const snarkjs = require('snarkjs') as any;
// eslint-disable-next-line @typescript-eslint/no-require-imports, @typescript-eslint/no-var-requires
const { buildPoseidon } = require('circomlibjs') as { buildPoseidon: () => Promise<any> };

// Path to compiled circuit artifacts (generated by veil-circuit/scripts/build.sh)
const CIRCUIT_DIR = path.join(__dirname, '../../../veil-circuit/build');

// BN254 field prime
const FIELD_PRIME = BigInt(
  '21888242871839275222246405745257275088696311157297823662689037894645226208583',
);

@Injectable()
export class VeilService {
  private readonly logger = new Logger(VeilService.name);
  private poseidon: any = null;
  private encKey: Buffer;

  // Soroban RPC + platform keypair (initialised lazily from config)
  private sorobanRpc: StellarSdk.rpc.Server | null = null;
  private platformKeypair: StellarSdk.Keypair | null = null;
  private poolContractId: string | null = null;
  private stellarNetwork: string = StellarSdk.Networks.TESTNET;

  constructor(
    @InjectRepository(ShieldedNote)
    private readonly noteRepo: Repository<ShieldedNote>,
    @InjectRepository(SpentNullifier)
    private readonly nullifierRepo: Repository<SpentNullifier>,
    private readonly config: ConfigService,
  ) {
    // Encryption key for stored notes (same key as BlockchainService uses)
    const hexKey = config.get<string>('SECRET_ENCRYPTION_KEY') ?? '';
    this.encKey = Buffer.from(hexKey.padEnd(64, '0').slice(0, 64), 'hex');

    // Soroban RPC setup
    const rpcUrl = config.get<string>('STELLAR_SOROBAN_RPC_URL');
    const secret = config.get<string>('STELLAR_PLATFORM_SECRET_KEY');
    const network = config.get<string>('STELLAR_NETWORK', 'testnet');
    this.poolContractId = config.get<string>('VEIL_POOL_CONTRACT_ID') ?? null;

    if (rpcUrl && secret) {
      this.sorobanRpc = new StellarSdk.rpc.Server(rpcUrl, { allowHttp: true });
      this.platformKeypair = StellarSdk.Keypair.fromSecret(secret);
      this.stellarNetwork =
        network === 'mainnet'
          ? StellarSdk.Networks.PUBLIC
          : StellarSdk.Networks.TESTNET;
    }
  }

  // ── Deposit ───────────────────────────────────────────────────────────────

  async deposit(dto: DepositDto): Promise<{
    noteId: string;
    commitment: string;
    amountUsdc: number;
    depositTxHash: string | null;
  }> {
    const poseidon = await this.getPoseidon();
    const amountMicro = BigInt(Math.round(dto.amountUsdc * 1_000_000));

    // Generate random secret + nullifier (31 bytes to stay within BN254 scalar field)
    const secret   = BigInt('0x' + crypto.randomBytes(31).toString('hex'));
    const nullifier = BigInt('0x' + crypto.randomBytes(31).toString('hex'));

    // commitment = Poseidon(secret, nullifier, amount)
    const commitmentField = poseidon([secret, nullifier, amountMicro]);
    const commitment = '0x' + poseidon.F.toObject(commitmentField).toString(16).padStart(64, '0');

    // Encrypt and store note
    const noteData = JSON.stringify({ secret: secret.toString(), nullifier: nullifier.toString() });
    const encryptedNote = this.encrypt(noteData);

    const note = this.noteRepo.create({
      userId: dto.userId ?? null,
      commitment,
      amountMicro: amountMicro.toString(),
      amountUsdc: dto.amountUsdc.toFixed(6),
      encryptedNote,
      status: ShieldedNoteStatus.PENDING,
    });
    await this.noteRepo.save(note);

    // Submit deposit to Soroban pool contract
    let depositTxHash: string | null = null;
    try {
      depositTxHash = await this.callPoolDeposit(
        commitment,
        amountMicro,
        note.id,
      );
      await this.noteRepo.update(note.id, {
        status: ShieldedNoteStatus.ACTIVE,
        depositTxHash,
        poolContractId: this.poolContractId,
      });
    } catch (err) {
      await this.noteRepo.update(note.id, { status: ShieldedNoteStatus.FAILED });
      throw new BadRequestException(
        `Pool deposit failed: ${(err as Error).message}`,
      );
    }

    this.logger.log(
      `Note deposited [id=${note.id}] [commitment=${commitment.slice(0, 12)}...] [tx=${depositTxHash}]`,
    );

    return { noteId: note.id, commitment, amountUsdc: dto.amountUsdc, depositTxHash };
  }

  // ── Pay Invoice ───────────────────────────────────────────────────────────

  async payInvoice(dto: PayInvoiceDto): Promise<{
    noteId: string;
    sorobanTxHash: string;
    nullifierHash: string;
  }> {
    const note = await this.noteRepo.findOne({ where: { id: dto.noteId } });
    if (!note) throw new NotFoundException(`Note ${dto.noteId} not found`);
    if (note.status !== ShieldedNoteStatus.ACTIVE) {
      throw new BadRequestException(`Note is ${note.status}, cannot pay`);
    }

    const noteAmountUsdc = parseFloat(note.amountUsdc);
    if (dto.invoiceAmountUsdc > noteAmountUsdc) {
      throw new BadRequestException(
        `Note amount ${noteAmountUsdc} USDC < invoice amount ${dto.invoiceAmountUsdc} USDC`,
      );
    }

    // Check off-chain double-spend cache
    const poseidon = await this.getPoseidon();
    const { secret, nullifier } = this.decryptNote(note.encryptedNote);
    const amountMicro = BigInt(note.amountMicro);

    const nullifierHashField = poseidon([BigInt(nullifier)]);
    const nullifierHash = '0x' + poseidon.F.toObject(nullifierHashField).toString(16).padStart(64, '0');

    const existing = await this.nullifierRepo.findOne({ where: { nullifierHash } });
    if (existing) {
      throw new BadRequestException('Note already spent (nullifier collision)');
    }

    // Generate ZK proof
    this.logger.log(`Generating ZK proof for note ${dto.noteId}...`);
    const { proof, publicSignals } = await this.generateProof({
      secret: BigInt(secret),
      nullifier: BigInt(nullifier),
      amount: amountMicro,
      commitment: note.commitment,
      invoiceRef: dto.invoiceRef,
      invoiceAmountMicro: BigInt(Math.round(dto.invoiceAmountUsdc * 1_000_000)),
    });

    // Submit withdrawal to Soroban contract
    const payAmountMicro = BigInt(Math.round(dto.invoiceAmountUsdc * 1_000_000));
    const sorobanTxHash = await this.callPoolWithdraw(
      proof,
      publicSignals,
      payAmountMicro,
      dto.invoiceRef,
    );

    // Record spent nullifier
    await this.nullifierRepo.save(
      this.nullifierRepo.create({
        nullifierHash,
        invoiceRef: dto.invoiceRef,
        sorobanTxHash,
      }),
    );
    await this.noteRepo.update(note.id, {
      status: ShieldedNoteStatus.SPENT,
      spentOnInvoice: dto.invoiceRef,
    });

    this.logger.log(
      `Invoice paid privately [ref=${dto.invoiceRef}] [tx=${sorobanTxHash}]`,
    );
    return { noteId: note.id, sorobanTxHash, nullifierHash };
  }

  // ── List notes ────────────────────────────────────────────────────────────

  async listNotes(userId: string): Promise<ShieldedNote[]> {
    return this.noteRepo.find({
      where: { userId, status: ShieldedNoteStatus.ACTIVE },
      order: { createdAt: 'DESC' },
      select: ['id', 'commitment', 'amountUsdc', 'status', 'createdAt', 'poolContractId'],
    });
  }

  // ── ZK proof generation ───────────────────────────────────────────────────

  private async generateProof(inputs: {
    secret: bigint;
    nullifier: bigint;
    amount: bigint;
    commitment: string;
    invoiceRef: string;
    invoiceAmountMicro: bigint;
  }): Promise<{ proof: any; publicSignals: string[] }> {
    const poseidon = await this.getPoseidon();

    const commitmentBig = BigInt(inputs.commitment);
    const nullifierHashField = poseidon([inputs.nullifier]);
    const nullifierHash = poseidon.F.toObject(nullifierHashField);

    // invoiceRefHash = Poseidon(invoiceRef as field element)
    const invoiceRefBytes = Buffer.from(inputs.invoiceRef);
    const invoiceRefBig = BigInt('0x' + invoiceRefBytes.toString('hex')) % FIELD_PRIME;
    const invoiceRefHashField = poseidon([invoiceRefBig]);
    const invoiceRefHash = poseidon.F.toObject(invoiceRefHashField);

    const circuitInput = {
      // Private
      secret:   inputs.secret.toString(),
      nullifier: inputs.nullifier.toString(),
      amount:   inputs.amount.toString(),
      // Public
      commitment:     commitmentBig.toString(),
      nullifierHash:  nullifierHash.toString(),
      invoiceAmount:  inputs.invoiceAmountMicro.toString(),
      invoiceRefHash: invoiceRefHash.toString(),
    };

    return snarkjs.groth16.fullProve(
      circuitInput,
      path.join(CIRCUIT_DIR, 'note_spend_js', 'note_spend.wasm'),
      path.join(CIRCUIT_DIR, 'note_spend_final.zkey'),
    );
  }

  // ── Soroban contract calls ────────────────────────────────────────────────

  private async callPoolDeposit(
    commitment: string,
    amountMicro: bigint,
    _noteId: string,
  ): Promise<string> {
    if (!this.sorobanRpc || !this.platformKeypair || !this.poolContractId) {
      this.logger.warn('Soroban not configured — skipping pool deposit (dev mode)');
      return 'dev-mode-no-tx';
    }

    const contract = new StellarSdk.Contract(this.poolContractId);
    const platformKey = this.platformKeypair.publicKey();

    const src = await this.sorobanRpc
      .getAccount(platformKey)
      .then((a) => new StellarSdk.Account(a.accountId(), a.sequenceNumber()));

    const commitmentBytes = Buffer.from(commitment.slice(2), 'hex');

    const rawTx = new StellarSdk.TransactionBuilder(src, {
      fee: '1000000',
      networkPassphrase: this.stellarNetwork,
    })
      .addOperation(
        contract.call(
          'deposit',
          StellarSdk.nativeToScVal(platformKey, { type: 'address' }),
          StellarSdk.xdr.ScVal.scvBytes(commitmentBytes),
          StellarSdk.nativeToScVal(amountMicro, { type: 'i128' }),
        ),
      )
      .setTimeout(300)
      .build();

    return this.submitSorobanTx(rawTx, 'callPoolDeposit');
  }

  private async callPoolWithdraw(
    proof: any,
    publicSignals: string[],
    amountMicro: bigint,
    invoiceRef: string,
  ): Promise<string> {
    if (!this.sorobanRpc || !this.platformKeypair || !this.poolContractId) {
      this.logger.warn('Soroban not configured — skipping pool withdraw (dev mode)');
      return 'dev-mode-no-tx';
    }

    // Encode proof as 256 bytes: A(64) || B(128) || C(64)
    const toHex32 = (n: string) => BigInt(n).toString(16).padStart(64, '0');
    const proofHex =
      toHex32(proof.pi_a[0]) + toHex32(proof.pi_a[1]) +
      toHex32(proof.pi_b[0][1]) + toHex32(proof.pi_b[0][0]) +
      toHex32(proof.pi_b[1][1]) + toHex32(proof.pi_b[1][0]) +
      toHex32(proof.pi_c[0]) + toHex32(proof.pi_c[1]);
    const proofBytes = Buffer.from(proofHex, 'hex');

    // Encode public inputs as Vec<Bytes32>
    const pubInputScVals = publicSignals.map((s) =>
      StellarSdk.xdr.ScVal.scvBytes(
        Buffer.from(BigInt(s).toString(16).padStart(64, '0'), 'hex'),
      ),
    );
    const pubInputsScVal = StellarSdk.xdr.ScVal.scvVec(pubInputScVals);

    const contract = new StellarSdk.Contract(this.poolContractId);
    const platformKey = this.platformKeypair.publicKey();

    const src = await this.sorobanRpc!
      .getAccount(platformKey)
      .then((a) => new StellarSdk.Account(a.accountId(), a.sequenceNumber()));

    const rawTx = new StellarSdk.TransactionBuilder(src, {
      fee: '5000000',
      networkPassphrase: this.stellarNetwork,
    })
      .addOperation(
        contract.call(
          'withdraw',
          StellarSdk.xdr.ScVal.scvBytes(proofBytes),
          pubInputsScVal,
          StellarSdk.nativeToScVal(amountMicro, { type: 'i128' }),
          StellarSdk.nativeToScVal(invoiceRef, { type: 'string' }),
        ),
      )
      .setTimeout(300)
      .build();

    return this.submitSorobanTx(rawTx, 'callPoolWithdraw');
  }

  private async submitSorobanTx(rawTx: any, opName: string): Promise<string> {
    const sim = await this.sorobanRpc!.simulateTransaction(rawTx);
    if (StellarSdk.rpc.Api.isSimulationError(sim)) {
      throw new Error(`${opName} simulation failed: ${sim.error}`);
    }

    const prepared = StellarSdk.rpc
      .assembleTransaction(rawTx, sim as StellarSdk.rpc.Api.SimulateTransactionSuccessResponse)
      .build();
    prepared.sign(this.platformKeypair!);

    const sent = await this.sorobanRpc!.sendTransaction(prepared);
    if (sent.status === 'ERROR') {
      throw new Error(`${opName} submit failed: ${JSON.stringify(sent.errorResult)}`);
    }

    // Poll for confirmation
    let result = await this.sorobanRpc!.getTransaction(sent.hash);
    let attempts = 0;
    while (
      result.status === StellarSdk.rpc.Api.GetTransactionStatus.NOT_FOUND &&
      attempts < 60
    ) {
      await new Promise((r) => setTimeout(r, 2000));
      result = await this.sorobanRpc!.getTransaction(sent.hash);
      attempts++;
    }

    if (result.status !== StellarSdk.rpc.Api.GetTransactionStatus.SUCCESS) {
      throw new Error(`${opName} did not confirm: status=${result.status}`);
    }

    return sent.hash;
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  private async getPoseidon(): Promise<any> {
    if (!this.poseidon) {
      this.poseidon = await buildPoseidon();
    }
    return this.poseidon;
  }

  private encrypt(plaintext: string): string {
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv('aes-256-gcm', this.encKey, iv);
    const encrypted = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
    const authTag = cipher.getAuthTag();
    return `${iv.toString('hex')}:${authTag.toString('hex')}:${encrypted.toString('hex')}`;
  }

  private decryptNote(encryptedNote: string): { secret: string; nullifier: string } {
    const [ivHex, authTagHex, ciphertextHex] = encryptedNote.split(':');
    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');
    const ciphertext = Buffer.from(ciphertextHex, 'hex');
    const decipher = crypto.createDecipheriv('aes-256-gcm', this.encKey, iv);
    decipher.setAuthTag(authTag);
    const plaintext = Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString('utf8');
    return JSON.parse(plaintext) as { secret: string; nullifier: string };
  }
}
