import type {
  MerchantDashboardPayload,
  Payment,
  SettlementsPayload,
} from '../types';

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000).toISOString();
const minsAgo = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();

/* ─── Dashboard ─────────────────────────────────────────── */

export const MOCK_DASHBOARD: MerchantDashboardPayload = {
  summaries: [
    { label: 'Gross revenue (7d)',  amount: '₦12,480,000', trend: '+18.4% vs prior week', tone: 'positive' },
    { label: 'Net settled (7d)',    amount: '₦11,793,600', trend: '+17.1% vs prior week', tone: 'positive' },
    { label: 'Pending payments',   amount: '₦1,240,000',  trend: '4 awaiting confirmation', tone: 'warning' },
    { label: 'Success rate',       amount: '96.3%',        trend: '-0.4% vs prior week',    tone: 'neutral'  },
  ],
  revenueSeries: [
    { label: 'Mon', gross: 1_420_000, settled: 1_340_000 },
    { label: 'Tue', gross: 1_850_000, settled: 1_750_000 },
    { label: 'Wed', gross: 1_620_000, settled: 1_530_000 },
    { label: 'Thu', gross: 2_100_000, settled: 1_985_000 },
    { label: 'Fri', gross: 1_980_000, settled: 1_870_000 },
    { label: 'Sat', gross: 2_340_000, settled: 2_210_000 },
    { label: 'Sun', gross: 1_170_000, settled: 1_108_600 },
  ],
  networkUsage: [
    { label: 'Stellar',     value: 54, color: '#D4A843', note: 'Primary settlement rail' },
    { label: 'EVM (Base)',  value: 31, color: '#60A5FA', note: 'Layer-2 EVM transactions' },
    { label: 'EVM (Polygon)', value: 15, color: '#A78BFA', note: 'Polygon PoS transactions' },
  ],
  settlementMix: [
    { label: 'Instant fiat',    value: 72, color: '#34D399', note: 'Converted to NGN' },
    { label: 'Hold digital $',  value: 28, color: '#D4A843', note: 'Retained as USDC' },
  ],
  recentActivity: [
    {
      id: 'act_1',
      type: 'payment',
      title: 'Payment confirmed — ₦480,000',
      note: 'Kora Wholesale · checkout_session · Stellar',
      at: minsAgo(4),
    },
    {
      id: 'act_2',
      type: 'settlement',
      title: 'Settlement pushed to Zenith Bank',
      note: '₦455,040 net · reference CHZ-29182',
      at: minsAgo(18),
    },
    {
      id: 'act_3',
      type: 'payment',
      title: 'Payment confirmed — ₦1,250,000',
      note: 'Dangote Flour Mills · invoice · EVM Base',
      at: minsAgo(37),
    },
    {
      id: 'act_4',
      type: 'api',
      title: 'API key rotated',
      note: 'sk_live_•••• replaced via dashboard',
      at: minsAgo(95),
    },
    {
      id: 'act_5',
      type: 'settlement',
      title: 'Settlement pushed to Zenith Bank',
      note: '₦1,181,250 net · reference CHZ-29177',
      at: minsAgo(160),
    },
    {
      id: 'act_6',
      type: 'risk',
      title: 'High-value payment flagged for review',
      note: '₦4,200,000 · awaiting manual approval',
      at: minsAgo(240),
    },
  ],
  averageSettlementSpeed: '~11 seconds',
};

/* ─── Payments ──────────────────────────────────────────── */

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay_001',
    reference: 'CHZ-PAY-29194',
    requestKind: 'checkout_session',
    createdAt: minsAgo(4),
    customerName: 'Kora Wholesale',
    customerEmail: 'ap@korawholesale.com',
    storeName: 'Demo Store',
    fiatAmount: '₦480,000.00',
    fiatCurrency: 'NGN',
    digitalDollarAmount: '300.00 USDC',
    settlementMode: 'instant_fiat',
    settlementCurrency: 'NGN',
    network: 'Stellar',
    speed: '~8s',
    costEfficiency: 'Low fee',
    status: 'settled',
    metadata: { orderId: 'ORD-4421' },
    callbackUrl: 'https://korawholesale.com/webhooks/cheesepay',
    expiresAt: daysAgo(-1),
  },
  {
    id: 'pay_002',
    reference: 'CHZ-PAY-29193',
    requestKind: 'invoice',
    createdAt: minsAgo(37),
    customerName: 'Dangote Flour Mills',
    customerEmail: 'finance@dangoteflour.com',
    storeName: 'Demo Store',
    fiatAmount: '₦1,250,000.00',
    fiatCurrency: 'NGN',
    digitalDollarAmount: '781.25 USDC',
    settlementMode: 'instant_fiat',
    settlementCurrency: 'NGN',
    network: 'EVM (Base)',
    speed: '~15s',
    costEfficiency: 'Standard',
    status: 'settled',
    metadata: { invoiceNo: 'INV-2024-0089' },
    callbackUrl: '',
    expiresAt: daysAgo(-1),
  },
  {
    id: 'pay_003',
    reference: 'CHZ-PAY-29192',
    requestKind: 'payment_link',
    createdAt: minsAgo(110),
    customerName: 'Shoprite Nigeria',
    customerEmail: 'treasury@shoprite.ng',
    storeName: 'Demo Store',
    fiatAmount: '₦320,000.00',
    fiatCurrency: 'NGN',
    digitalDollarAmount: '200.00 USDC',
    settlementMode: 'hold_usdc',
    settlementCurrency: 'USD',
    network: 'Stellar',
    speed: '~9s',
    costEfficiency: 'Low fee',
    status: 'confirmed',
    metadata: {},
    callbackUrl: '',
    expiresAt: daysAgo(-1),
  },
  {
    id: 'pay_004',
    reference: 'CHZ-PAY-29191',
    requestKind: 'checkout_session',
    createdAt: minsAgo(180),
    customerName: 'MTN Nigeria',
    customerEmail: 'ap@mtn.ng',
    storeName: 'Demo Store',
    fiatAmount: '₦4,200,000.00',
    fiatCurrency: 'NGN',
    digitalDollarAmount: '2,625.00 USDC',
    settlementMode: 'instant_fiat',
    settlementCurrency: 'NGN',
    network: 'EVM (Polygon)',
    speed: '~20s',
    costEfficiency: 'Standard',
    status: 'pending',
    metadata: { orderId: 'ORD-MTN-8812' },
    callbackUrl: 'https://mtn.ng/payments/callback',
    expiresAt: daysAgo(-0.5),
  },
  {
    id: 'pay_005',
    reference: 'CHZ-PAY-29188',
    requestKind: 'invoice',
    createdAt: daysAgo(1),
    customerName: 'Interswitch Group',
    customerEmail: 'finance@interswitch.com',
    storeName: 'Demo Store',
    fiatAmount: '₦780,000.00',
    fiatCurrency: 'NGN',
    digitalDollarAmount: '487.50 USDC',
    settlementMode: 'instant_fiat',
    settlementCurrency: 'NGN',
    network: 'Stellar',
    speed: '~7s',
    costEfficiency: 'Low fee',
    status: 'settled',
    metadata: { invoiceNo: 'INV-2024-0088' },
    callbackUrl: '',
    expiresAt: daysAgo(-2),
  },
  {
    id: 'pay_006',
    reference: 'CHZ-PAY-29185',
    requestKind: 'qr_dynamic',
    createdAt: daysAgo(1),
    customerName: 'Nestle Nigeria',
    customerEmail: 'procurement@nestle.ng',
    storeName: 'Demo Store',
    fiatAmount: '₦92,000.00',
    fiatCurrency: 'NGN',
    digitalDollarAmount: '57.50 USDC',
    settlementMode: 'instant_fiat',
    settlementCurrency: 'NGN',
    network: 'Stellar',
    speed: '~9s',
    costEfficiency: 'Low fee',
    status: 'expired',
    metadata: {},
    callbackUrl: '',
    expiresAt: daysAgo(0.5),
  },
  {
    id: 'pay_007',
    reference: 'CHZ-PAY-29180',
    requestKind: 'checkout_session',
    createdAt: daysAgo(2),
    customerName: 'Access Bank PLC',
    customerEmail: 'treasury@accessbank.com',
    storeName: 'Demo Store',
    fiatAmount: '₦2,100,000.00',
    fiatCurrency: 'NGN',
    digitalDollarAmount: '1,312.50 USDC',
    settlementMode: 'hold_usdc',
    settlementCurrency: 'USD',
    network: 'EVM (Base)',
    speed: '~14s',
    costEfficiency: 'Standard',
    status: 'settled',
    metadata: { orderId: 'ORD-ACC-3301' },
    callbackUrl: 'https://accessbank.com/webhook/cheesepay',
    expiresAt: daysAgo(-3),
  },
  {
    id: 'pay_008',
    reference: 'CHZ-PAY-29174',
    requestKind: 'api_request',
    createdAt: daysAgo(3),
    customerName: 'Flutterwave Inc.',
    customerEmail: 'settlements@flutterwave.com',
    storeName: 'Demo Store',
    fiatAmount: '₦560,000.00',
    fiatCurrency: 'NGN',
    digitalDollarAmount: '350.00 USDC',
    settlementMode: 'instant_fiat',
    settlementCurrency: 'NGN',
    network: 'Stellar',
    speed: '~8s',
    costEfficiency: 'Low fee',
    status: 'failed',
    metadata: { reason: 'wallet_insufficient_balance' },
    callbackUrl: 'https://api.flutterwave.com/hooks/cheese',
    expiresAt: daysAgo(2),
  },
];

/* ─── Settlements ───────────────────────────────────────── */

export const MOCK_SETTLEMENTS: SettlementsPayload = {
  summaries: [
    { label: 'Total settled (30d)', amount: '₦48,320,000', trend: '+22.1% vs prior month', tone: 'positive' },
    { label: 'Avg. settlement fee', amount: '0.55%',        trend: 'Competitive rail routing', tone: 'neutral'  },
    { label: 'Next payout ETA',     amount: '< 15 sec',     trend: 'Instant schedule active',  tone: 'positive' },
  ],
  currentFxRate: '1 USDC = ₦1,598.40',
  estimatedArrival: '~11 seconds via Stellar',
  payoutAccounts: [
    {
      id: 'acct_001',
      label: 'Zenith Bank — Main',
      accountType: 'bank',
      currency: 'NGN',
      destination: '2109488301 · Zenith Bank PLC',
      status: 'active',
      defaultForInstantPayout: true,
    },
    {
      id: 'acct_002',
      label: 'USDC Treasury Wallet',
      accountType: 'digital_dollar',
      currency: 'USD',
      destination: 'GDQP2K...FHZQ · Stellar',
      status: 'active',
      defaultForInstantPayout: false,
    },
  ],
  settlements: [
    {
      id: 'stl_001',
      paymentReference: 'CHZ-PAY-29194',
      currency: 'NGN',
      grossAmount: '₦480,000.00',
      netAmount: '₦477,360.00',
      destination: 'Zenith Bank — Main',
      schedule: 'instant',
      eta: '~11s',
      status: 'settled',
      createdAt: minsAgo(4),
      bankReference: 'ZBL-20240515-0082',
    },
    {
      id: 'stl_002',
      paymentReference: 'CHZ-PAY-29193',
      currency: 'NGN',
      grossAmount: '₦1,250,000.00',
      netAmount: '₦1,243,125.00',
      destination: 'Zenith Bank — Main',
      schedule: 'instant',
      eta: '~11s',
      status: 'settled',
      createdAt: minsAgo(37),
      bankReference: 'ZBL-20240515-0081',
    },
    {
      id: 'stl_003',
      paymentReference: 'CHZ-PAY-29188',
      currency: 'NGN',
      grossAmount: '₦780,000.00',
      netAmount: '₦775,710.00',
      destination: 'Zenith Bank — Main',
      schedule: 'instant',
      eta: '~11s',
      status: 'settled',
      createdAt: daysAgo(1),
      bankReference: 'ZBL-20240514-0077',
    },
    {
      id: 'stl_004',
      paymentReference: 'CHZ-PAY-29180',
      currency: 'USD',
      grossAmount: '1,312.50 USDC',
      netAmount: '1,305.23 USDC',
      destination: 'USDC Treasury Wallet',
      schedule: 'instant',
      eta: '—',
      status: 'settled',
      createdAt: daysAgo(2),
      bankReference: '—',
    },
    {
      id: 'stl_005',
      paymentReference: 'CHZ-PAY-29174',
      currency: 'NGN',
      grossAmount: '₦560,000.00',
      netAmount: '₦556,920.00',
      destination: 'Zenith Bank — Main',
      schedule: 'instant',
      eta: '—',
      status: 'failed',
      createdAt: daysAgo(3),
      bankReference: '—',
    },
  ],
};
